spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    database: mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1 FROM DUAL
      schema: examples
      max-lifetime: 1200000
    url: jdbc:mysql://39.107.244.193:3306/examples?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  # redis 配置
  redis:
    # 地址
    host: 39.107.244.193
    # 端口，默认为6379
    port: 6379
    # 密码
    password: root
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 日志配置
logging:
  level:
    org.zuoyu.examples: debug
    org.springframework: info

swagger:
  config:
    enabled: true
    urlTemplating: false
    forCodeGen: false

browser:
  auto:
    enable: true
    url: ""
