server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 200
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 25

# Spring配置
spring:
  profiles:
    active: dev

swagger:
  config:
    enabled: true
    urlTemplating: true
    forCodeGen: true
